/** @type {import('tailwindcss').Config} */
export default {
    darkMode: "class",
    content: [
      "./index.html",
      "./src/**/*.{js,ts,jsx,tsx}",
    ],
    theme: {
        extend: {
            "colors": {
                "error": "#ffb4ab",
                "on-tertiary-fixed": "#400013",
                "on-secondary": "#00391e",
                "on-secondary-container": "#8ec59f",
                "on-primary-fixed-variant": "#881a34",
                "on-tertiary": "#660324",
                "surface-container-highest": "#3a3335",
                "tertiary-fixed-dim": "#ffb2bd",
                "surface-variant": "#3a3335",
                "surface-tint": "#ffb2ba",
                "inverse-surface": "#ecdfe2",
                "tertiary-container": "#b2425a",
                "surface-container": "#251e20",
                "on-error": "#690005",
                "surface": "#181214",
                "secondary-fixed": "#b7f0c7",
                "primary": "#ffb2ba",
                "surface-container-low": "#201a1c",
                "on-tertiary-fixed-variant": "#851f39",
                "secondary-fixed-dim": "#9cd3ac",
                "surface-container-lowest": "#120d0f",
                "primary-container": "#b73e54",
                "on-error-container": "#ffdad6",
                "inverse-primary": "#a9334a",
                "secondary": "#9cd3ac",
                "on-secondary-fixed-variant": "#1b5033",
                "on-primary": "#67001f",
                "outline": "#a58a8c",
                "background": "#181214",
                "on-primary-fixed": "#400010",
                "on-background": "#ecdfe2",
                "secondary-container": "#1e5335",
                "on-surface": "#ecdfe2",
                "on-surface-variant": "#debfc1",
                "on-tertiary-container": "#ffe3e5",
                "error-container": "#93000a",
                "primary-fixed": "#ffd9dc",
                "surface-bright": "#3f3739",
                "on-primary-container": "#ffe3e5",
                "surface-container-high": "#2f282a",
                "tertiary": "#ffb2bd",
                "primary-fixed-dim": "#ffb2ba",
                "inverse-on-surface": "#362e31",
                "on-secondary-fixed": "#00210f",
                "outline-variant": "#574143",
                "tertiary-fixed": "#ffd9dd",
                "surface-dim": "#181214"
            },
            "borderRadius": {
                "DEFAULT": "0.25rem",
                "lg": "0.5rem",
                "xl": "0.75rem",
                "full": "9999px"
            },
            "spacing": {
                "unit": "8px",
                "container-max": "1280px",
                "margin-mobile": "20px",
                "gutter": "32px",
                "margin-desktop": "64px",
                "section-gap": "120px"
            },
            "fontFamily": {
                "display-hero": ["Cormorant Garamond"],
                "data-label": ["IBM Plex Mono"],
                "headline-lg": ["Playfair Display"],
                "body-md": ["Source Serif 4"],
                "headline-md": ["Playfair Display"],
                "body-lg": ["Source Serif 4"],
                "headline-lg-mobile": ["Playfair Display"],
                "data-value": ["IBM Plex Mono"]
            },
            "fontSize": {
                "display-hero": ["64px", {"lineHeight": "1.1", "letterSpacing": "-0.02em", "fontWeight": "300"}],
                "data-label": ["14px", {"lineHeight": "1.2", "letterSpacing": "0.05em", "fontWeight": "500"}],
                "headline-lg": ["40px", {"lineHeight": "1.2", "fontWeight": "600"}],
                "body-md": ["16px", {"lineHeight": "1.5", "fontWeight": "400"}],
                "headline-md": ["28px", {"lineHeight": "1.3", "fontWeight": "500"}],
                "body-lg": ["18px", {"lineHeight": "1.6", "fontWeight": "400"}],
                "headline-lg-mobile": ["32px", {"lineHeight": "1.2", "fontWeight": "600"}],
                "data-value": ["18px", {"lineHeight": "1.1", "fontWeight": "600"}]
            }
        },
    },
};
